field: 5d18585b-1193-4b44-a30c-27441416cdeb # ab-wann-mpu
fieldLayouts:
  c4a8b685-f6ed-472a-93cb-9962a5c00555:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1ab0babd-212b-4220-8f1c-382a87d6c520 # ab-wann-mpu 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af815be9-995e-48bf-9a08-de9359914960
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 28f274d6-a264-4eb6-b125-19116c734026
        userCondition: null
fields:
  1ab0babd-212b-4220-8f1c-382a87d6c520: # ab-wann-mpu 
    columnSuffix: dsyujfch
    contentColumnType: text
    fieldGroup: null
    handle: abWannMpu
    instructions: null
    name: 'ab-wann-mpu '
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: abWannMpu
name: ab-wann-mpu
sortOrder: 1
