field: 51fe5c31-52c5-4f6b-86c1-f153439cfaf1 # deneme
fieldLayouts:
  f7cb8cde-a98e-494a-bb05-ee9b39437f2f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d98e95db-9be7-47e4-80ad-909cc5336d4a # Deneme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f6ffbdb4-8aaa-4a3e-9bca-75fe11366f69
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ecf033f0-2562-45ef-99ed-e00927801f45
        userCondition: null
fields:
  d98e95db-9be7-47e4-80ad-909cc5336d4a: # Deneme
    columnSuffix: hudygrbf
    contentColumnType: text
    fieldGroup: null
    handle: deneme
    instructions: null
    name: Deneme
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: deneme
name: Deneme
sortOrder: 1
