field: bc42ffe9-bb41-4cdb-924c-556c84fa78dd # Häufige Fragen
fieldLayouts:
  d6529ebd-dc4a-48be-baa4-faf879c8b465:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 997e02d6-6635-478c-b49e-7e904cfac1a3 # Häufige Fragen
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ea95c85-de51-44fb-9d0f-c1e93288c1fc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 19f9467a-121a-4ecf-9e40-e5cb8ae4ea8d
        userCondition: null
fields:
  997e02d6-6635-478c-b49e-7e904cfac1a3: # Häufige Fragen
    columnSuffix: vfhuuicb
    contentColumnType: text
    fieldGroup: null
    handle: haufigeFragen
    instructions: null
    name: 'Häufige Fragen'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: haufigeFragen
name: 'Häufige Fragen'
sortOrder: 1
