field: f84adf17-a265-4b33-a406-704b52c0d014 # kontakt
fieldLayouts:
  70308ecf-e023-4c23-8d12-2d0f27943c65:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d9b4ba5e-d25d-44cf-9035-61ca26179973 # kontakt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d81c0ef-cf29-42f6-856d-ca3e586b4980
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 667816dd-cd91-4a2a-9f2d-5a1796dac6e5
        userCondition: null
fields:
  d9b4ba5e-d25d-44cf-9035-61ca26179973: # kontakt
    columnSuffix: cnvljavo
    contentColumnType: text
    fieldGroup: null
    handle: kontakt
    instructions: null
    name: kontakt
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: kontakt
name: kontakt
sortOrder: 1
