field: 512e2ce2-2310-4d2f-8628-45c24ee51abb # leistungen
fieldLayouts:
  b2cf629a-cb00-4d11-8d91-da8df40ae563:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 580c03b3-2f98-4a26-b1f7-bedb2c8b91c5 # leistungen/_entry
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f11bc7a3-6b5b-4579-8bcc-7b2ea546fbb2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4b3c5b4e-ee29-4abc-8ec1-f8f5abbc1d42 # burada
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 137ba30d-86bc-4761-b801-3e07ebf2dde8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5b7d0355-9df0-4321-b934-034f1386b291
        userCondition: null
fields:
  4b3c5b4e-ee29-4abc-8ec1-f8f5abbc1d42: # burada
    columnSuffix: gnabekks
    contentColumnType: text
    fieldGroup: null
    handle: burada
    instructions: null
    name: burada
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  580c03b3-2f98-4a26-b1f7-bedb2c8b91c5: # leistungen/_entry
    columnSuffix: bigekcjn
    contentColumnType: text
    fieldGroup: null
    handle: leistungenEntry
    instructions: null
    name: leistungen/_entry
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: leistungenEntry
name: leistungen/_entry
sortOrder: 1
