field: 6a307bef-ccd0-480d-9aa4-f6427d4a604b # mpu-abstinenznachweis
fieldLayouts:
  6a37e260-3e1a-46c1-8864-53ccee6646e7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e096d16d-9ab1-46ab-8020-8d3bbb0f7254 # mpu-abstinenznachweis
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a640c3d-5d5a-4781-993c-162653943250
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4770c458-8daf-4e23-ab22-c41ad1808a4f
        userCondition: null
fields:
  e096d16d-9ab1-46ab-8020-8d3bbb0f7254: # mpu-abstinenznachweis
    columnSuffix: jqfqhayt
    contentColumnType: text
    fieldGroup: null
    handle: mpuAbstinenznachweis
    instructions: null
    name: mpu-abstinenznachweis
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: mpuAbstinenznachweis
name: mpu-abstinenznachweis
sortOrder: 1
