field: 6f8add5d-184e-4fee-950f-45b1e045f7f5 # mpu-nicht-bestanden
fieldLayouts:
  50217762-1c22-474b-85d9-f9fa393390d8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cfee86f7-46f4-4965-9872-124c7cdde921 # mpu-nicht-bestanden
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 984ac2ec-7b07-42f9-acac-7486001896f3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: aeccfd4b-e8f0-42bc-8231-66185faabfef
        userCondition: null
fields:
  cfee86f7-46f4-4965-9872-124c7cdde921: # mpu-nicht-bestanden
    columnSuffix: tswfgfuj
    contentColumnType: text
    fieldGroup: null
    handle: mpuNichtBestanden
    instructions: null
    name: mpu-nicht-bestanden
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: mpuNichtBestanden
name: mpu-nicht-bestanden
sortOrder: 1
