field: 85b576dc-96db-4ff4-8c32-314e674efdea # recipe contents
fieldLayouts:
  7cff6bd5-4853-4a8c-90a9-a8f872dbe7c3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ffebc996-f08f-462f-8b9b-e844f113f572 # Bosy Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28243e7d-91aa-4883-81f5-c96efb501c6b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2c858fca-cf5e-47b8-a66d-1eb3dc949969
        userCondition: null
fields:
  ffebc996-f08f-462f-8b9b-e844f113f572: # Bosy Content
    columnSuffix: wfkwxacq
    contentColumnType: text
    fieldGroup: null
    handle: bosyContent
    instructions: null
    name: 'Bosy Content'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: recipeCopy
name: 'recipe Copy'
sortOrder: 3
