field: 85b576dc-96db-4ff4-8c32-314e674efdea # recipe contents
fieldLayouts:
  14372bf1-3d3c-4f71-85cb-a5d859979326:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: db3e292b-a49f-474e-9ec6-064ab7da7c3a # Steps Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af52bc8b-f310-454d-a638-391874857389
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8950dd3d-3188-4384-a9cb-2b511fdfe37e # Steps content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d3fb9d5e-dc9b-4d6f-aab2-a99c6c02f6c1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6ab11dd4-5654-403e-ba73-2716abd2e503
        userCondition: null
fields:
  8950dd3d-3188-4384-a9cb-2b511fdfe37e: # Steps content
    columnSuffix: dxtispva
    contentColumnType: text
    fieldGroup: null
    handle: stepsContent
    instructions: null
    name: 'Steps content'
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - 'steps Instructions '
                -
                  - handle
                  - stepsInstructions
                -
                  - width
                  - ''
                -
                  - type
                  - multiline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
      maxRows: null
      minRows: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  db3e292b-a49f-474e-9ec6-064ab7da7c3a: # Steps Title
    columnSuffix: oqfltbqb
    contentColumnType: text
    fieldGroup: null
    handle: stepsTitle
    instructions: null
    name: 'Steps Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: recipeSteps
name: 'recipe Steps'
sortOrder: 4
