field: 85b576dc-96db-4ff4-8c32-314e674efdea # recipe contents
fieldLayouts:
  db667c1f-29e6-4a35-9635-78c9354c316c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d539e8ca-720e-4154-98e5-56ed56b69e6e # ingredients
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db168a91-95dd-429e-81fc-5b5bac829408
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5f976b8b-17bf-4b8c-abd2-fe6225347b2e
        userCondition: null
fields:
  d539e8ca-720e-4154-98e5-56ed56b69e6e: # ingredients
    columnSuffix: dizyztib
    contentColumnType: text
    fieldGroup: null
    handle: ingredients
    instructions: null
    name: ingredients
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - amount
                -
                  - handle
                  - amount
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - 'Ingredient '
                -
                  - handle
                  - ingredient
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults: null
      maxRows: null
      minRows: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
handle: recipesIngredients
name: 'recipes ingredients'
sortOrder: 5
