field: 72e4e202-3cec-4974-8760-bc1eb6a25d4c # sperrfrist
fieldLayouts:
  3bf5d3a5-81dc-4ed9-885b-ab7ecce66e30:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cf321b76-b07d-4913-9199-585dfa88be9f # sperrfrist
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db6f866e-caa7-4f27-9240-b42e3ee3285d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5c2923d9-e5f2-439a-af9f-fd3d2ad4fbbc
        userCondition: null
fields:
  cf321b76-b07d-4913-9199-585dfa88be9f: # sperrfrist
    columnSuffix: xrlrkzjv
    contentColumnType: text
    fieldGroup: null
    handle: sperrfrist
    instructions: null
    name: sperrfrist
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: sperrfrist
name: sperrfrist
sortOrder: 1
