field: 31ea97cc-2540-43ac-8cdf-6fff91920380 # rich Text
fieldLayouts:
  1746aa6c-59b3-4804-bd8e-f5bebcaddcd5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2613f612-11a1-43c8-bcbc-4e49a9e32fc6 # Über uns
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47d52be0-2825-437b-bd4d-b7b225e1c7f5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 375ab4ff-9035-4403-921a-269955a0f3f0
        userCondition: null
fields:
  2613f612-11a1-43c8-bcbc-4e49a9e32fc6: # Über uns
    columnSuffix: nmatsazv
    contentColumnType: text
    fieldGroup: null
    handle: uberUns
    instructions: null
    name: 'Über uns'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: uberUns
name: 'Über uns'
sortOrder: 1
