fieldLayouts:
  80ea2960-865a-4dcc-ad66-2230c0ec35a9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bf5bfa85-4b2a-4be0-96ce-cad791465559
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 207f10e6-f0ff-45e4-b631-8df9eb777a79
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: b7fdf6f0-594f-404a-b82d-fde412bc7b02 # blog
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
