fieldLayouts:
  72b45429-55eb-42c6-a3df-8b4f6f778713:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 59d6da25-f2f0-4e28-8a29-73ca4125b5c3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4a47564f-6e57-462c-a4e1-4cfad60caba7
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 33d4e91d-25b3-4bf3-b8a7-b32dcd57170d # Datenschutz
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
