defaultPlacement: end
enableVersioning: true
handle: deneme
name: 'deneme '
propagationMethod: all
siteSettings:
  cfc2c24c-39ec-4be4-adfd-3efaa2770e92: # hamburg-mpu
    enabledByDefault: true
    hasUrls: true
    template: deneme/_entry
    uriFormat: 'deneme/{slug}'
type: channel
