defaultPlacement: end
enableVersioning: true
handle: faq
name: FAQ
propagationMethod: all
siteSettings:
  cfc2c24c-39ec-4be4-adfd-3efaa2770e92: # hamburg-mpu
    enabledByDefault: true
    hasUrls: true
    template: faq/_entry
    uriFormat: 'faq/{slug}'
type: channel
