defaultPlacement: end
enableVersioning: true
handle: impressum
name: Impressum
propagationMethod: all
siteSettings:
  cfc2c24c-39ec-4be4-adfd-3efaa2770e92: # hamburg-mpu
    enabledByDefault: true
    hasUrls: true
    template: impressum/_entry
    uriFormat: 'impressum/{slug}'
type: channel
