defaultPlacement: end
enableVersioning: true
handle: kannManDieMpuUmgehen
name: 'Kann man die MPU umgehen'
propagationMethod: all
siteSettings:
  cfc2c24c-39ec-4be4-adfd-3efaa2770e92: # hamburg-mpu
    enabledByDefault: true
    hasUrls: true
    template: kann-man-die-mpu-umgehen/_entry
    uriFormat: 'kann-man-die-mpu-umgehen/{slug}'
type: channel
