defaultPlacement: end
enableVersioning: true
handle: kontakt
name: Kontakt
propagationMethod: all
siteSettings:
  cfc2c24c-39ec-4be4-adfd-3efaa2770e92: # hamburg-mpu
    enabledByDefault: true
    hasUrls: true
    template: kontakt/_entry
    uriFormat: 'kontakt/{slug}'
type: channel
