defaultPlacement: end
enableVersioning: true
handle: kosten
name: Kosten
propagationMethod: all
siteSettings:
  cfc2c24c-39ec-4be4-adfd-3efaa2770e92: # hamburg-mpu
    enabledByDefault: true
    hasUrls: true
    template: kosten/_entry
    uriFormat: 'kosten/{slug}'
type: channel
