defaultPlacement: end
enableVersioning: true
handle: leistungen
name: Leistungen
propagationMethod: all
siteSettings:
  cfc2c24c-39ec-4be4-adfd-3efaa2770e92: # hamburg-mpu
    enabledByDefault: true
    hasUrls: true
    template: leistungen/_entry
    uriFormat: 'leistungen/{slug}'
type: channel
