defaultPlacement: end
enableVersioning: true
handle: mpuGutachtenKaufen
name: 'MPU Gutachten kaufen'
propagationMethod: all
siteSettings:
  cfc2c24c-39ec-4be4-adfd-3efaa2770e92: # hamburg-mpu
    enabledByDefault: true
    hasUrls: true
    template: mpu-gutachten-kaufen/_entry
    uriFormat: 'mpu-gutachten-kaufen/{slug}'
type: channel
