defaultPlacement: end
enableVersioning: true
handle: mpuNichtBestanden
name: 'MPU nicht bestanden'
propagationMethod: all
siteSettings:
  cfc2c24c-39ec-4be4-adfd-3efaa2770e92: # hamburg-mpu
    enabledByDefault: true
    hasUrls: true
    template: mpu-nicht-bestanden/_entry
    uriFormat: 'mpu-nicht-bestanden/{slug}'
type: channel
