defaultPlacement: end
enableVersioning: true
handle: mpuVerjahrung
name: 'MPU Verjährung'
propagationMethod: all
siteSettings:
  cfc2c24c-39ec-4be4-adfd-3efaa2770e92: # hamburg-mpu
    enabledByDefault: true
    hasUrls: true
    template: mpu-verjahrung/_entry
    uriFormat: 'mpu-verjahrung/{slug}'
type: channel
