defaultPlacement: end
enableVersioning: true
handle: sperrfrist
name: Sperrfrist
propagationMethod: all
siteSettings:
  cfc2c24c-39ec-4be4-adfd-3efaa2770e92: # hamburg-mpu
    enabledByDefault: true
    hasUrls: true
    template: sperrfrist/_entry
    uriFormat: 'sperrfrist/{slug}'
type: channel
