defaultPlacement: end
enableVersioning: true
handle: uberUns
name: 'über uns'
propagationMethod: all
siteSettings:
  cfc2c24c-39ec-4be4-adfd-3efaa2770e92: # hamburg-mpu
    enabledByDefault: true
    hasUrls: true
    template: uber-uns/_entry
    uriFormat: 'uber-uns/{slug}'
type: channel
